pipeline {
    agent any
    
    environment {
        SONAR_TOKEN = credentials('sonar-token')
    }

    stages {
        stage('Build') {
            steps {
                sh "./mvnw -B clean verify sonar:sonar -Dsonar.projectKey=locations-app -Dsonar.host.url=http://sonarqube:9000 -Dsonar.login=${SONAR_TOKEN} -Dsonar.projectVersion=1.0.0-${BUILD_NUMBER}"
            }
        }
    }
}